### PR TITLE
Db url special chars fix | Undefined options.db.rul fix | READY FOR MERGE

### LINKED ISSUE #668: Config hoodie/dbUrl not accepted when password contains some special chars
Let's say dbUrl is set to https://USERNAME:PASSWORD@ACCOUNTNAME.cloudant.com/

If PASSWORD contains is too complicated (contains slashes, semicolon - chars have to be discovered as I did not test them specifically!) the app cannot start and the following error is thrown:

Error: Authentication details missing from database URL

### LINKED ISSUE #699: options.db.url is not specified
Where does options.db.url is being initialized and set, in order to be used at https://github.com/hoodiehq/hoodie/blob/master/cli/parse-options.js#L51 ?

Is that some sort of left-over code from previous fixes? Have I found a bug?

### PR DESCRIPTION
**Pull request by Manosmer**
Fixes #668. Also, fixes #699, because the test case for lacking of auth details in dbUrl is covered in function createAuthDbUrl and if(parseUrl(options.dbUrl).auth) case (which contained options.db.url) is never reachable and was removed.

### CODE REVIEW

File: bin/start.js [hunk 1]
```diff
@@ -1,11 +1,15 @@
...
+var log = require('npmlog')
+log.level = 'warn'
+
 var cli = require('../cli')
 
 var emoji = require('node-emoji')
 
 cli(function (error, server) {
   if (error) {
+    log.warn('DB url config', 'If you are using --dbUrl, --dbUrlUsername, --dbUrlPassword, you should provide your authentication details without URL encoding')
```
Comment (gr2m) [inline bin/start.js]: There can be many errors that can returned by the `cli` callback, we cannot assume that is related to the DB url config. I think this is the wrong place to log this

Comment (gr2m) [inline bin/start.js]: There can be many errors that can be returned by the cli callback, we cannot assume that is related to the DB url config. I think this is the wrong place to log this

File: cli/options.js [hunk 2]
```diff
@@ -67,7 +67,17 @@ function getCliOptions (projectPath) {
...
+      },
+      dbUrlPassword: {
+        type: 'string',
+        default: defaults.dbUrlPassword,
+        describe: 'Provides the password (if required) for auth with the db at dbUrl (requires dbUrl and/or dbUrlUsername)'
+      },
+      dbUrlUsername: {
+        type: 'string',
+        default: defaults.dbUrlUsername,
+        describe: 'Provides the username (if required) for auth with the db at dbUrl (requires dbUrl and dbUrlPassword)'
```
Comment (gr2m) [inline cli/options.js]: note that username & password are always required by Hoodie

File: cli/parse-options.js [hunk 3]
```diff
@@ -20,9 +19,89 @@ var urlParse = require('url').parse
  * PouchDB is being used. A shortcut to set PouchDB’s adapter to memdown is to
  * passe set the `inMemory: true` option. If it’s not set, leveldown is used
  * with the prefix set to `options.data` + 'data' (`.hoodie/data` by default).
+ *
+ * @function createAuthDbUrl accepts options.dbUrlUsername, options.dbUrlPassword, options.dbUrl, @returns encoded dbUrl
```
Comment (gr2m) [inline cli/parse-options.js]: we don’t use these `@function` or `@returns` tags anywhere yet. I don’t mind starting to do them, we were looking into tools to generate API docs out of comments. But I’d coordinate the two: the `@name` tags with a tool that can parse them and generate docs out of them.

I suggest we make a follow up issue for this, and for the time being do not use the tags, as their usage implies that we have some API docs generator?

File: cli/parse-options.js [hunk 4]
```diff
@@ -20,9 +19,89 @@ var urlParse = require('url').parse
...
+   * @param dbUsername used for parsing options.dbUrlUsername
+   * @param dbPassword used for parsing options.dbUrlPassword
+   * @param dbUrl used for parsing options.dbUrl
+   *
+   * @var dbUrlParts contains different parts of dbUrl, helping in modifing username and password
+   *
+   * @returns dbUrl based on the parameters
+   * @throws Error if dbUrl is unparsable or authDetails are missing
+   */
+  function createAuthDbUrl (dbUsername, dbPassword, dbUrl) {
```
Comment (gr2m) [inline cli/parse-options.js]: we try to avoid defining a function within another function. This one is quite big, can you move it into `cli/utils/create-auth-db-url.js`?

File: test/unit/cli/parse-options-test.js [hunk 5]
```diff
@@ -68,6 +72,57 @@ test('parse options', function (group) {
...
+    var config = parseOptions({
+      public: 'public',
+      data: 'data',
+      dbUrl: 'https://https://foo@baz.com'
+    })
+    var defaults = config.PouchDB('hack', {skip_setup: true}).__opts
+    t.is(defaults.prefix, 'https://https:%2F%2Ffoo@baz.com', 'Sets config.db.url')
+
+    t.end()
+  })
```
Comment (gr2m) [inline test/unit/cli/parse-options-test.js:100]: does that test make sense? Is the double `https://https` an accident?

File: test/unit/cli/parse-options-test.js [hunk 6]
```diff
@@ -68,6 +72,57 @@ test('parse options', function (group) {
     t.end()
   })
 
+  group.test('dbUrl', function (t) {
```
Comment (gr2m) [inline test/unit/cli/parse-options-test.js]: can you make the test labels more descriptive? Like `dbUrl with encrypted url encoded username` etc?

File: test/unit/cli/parse-options-test.js [hunk 7]
```diff
@@ -68,6 +72,57 @@ test('parse options', function (group) {
...
+    var config = parseOptions({
+      public: 'public',
+      data: 'data',
+      dbUrl: 'http://dasds@dasdsa.com:@dsadas@dasdas@@baz.com'
+    })
+    var defaults = config.PouchDB('hack', {skip_setup: true}).__opts
+    t.is(defaults.prefix, 'http://dasds%40dasdsa.com:%40dsadas%40dasdas%40@baz.com', 'Sets config.db.url')
+
+    t.end()
+  })
```
Comment (gr2m) [inline test/unit/cli/parse-options-test.js]: can you add a test that has both auth in the URL but also passes `dbUrlUsername` and `dbUrlPassword` so we can define how Hoodie is supposed to behave in such a case?

**Comment by Manosmer** [comment]
Hello @gr2m 😄. Did you delete your comment? Because I can't find it anymore. Also, I am adding myself some new test cases in parse-options-test.js. I am not finished with that one yet. So, the coverage will be raised again to 99%. The PR was made in order to make you able to review my code and make a request or change before the merge.

**Review by gr2m — CHANGES_REQUESTED** [review]

**Comment by gr2m** [comment]
@Litarhis so sorry I removed the comment to make it part of my review and then forgot to actually submit my review lol

File: bin/start.js (hunk 1 above)
Comment (Manosmer) [reply bin/start.js]: Thought so too. Do you have any opinion about where to put that warning?

File: cli/parse-options.js (hunk 3 above)
Comment (Manosmer) [reply cli/parse-options.js]: Got it!

File: test/unit/cli/parse-options-test.js (hunk 6 above)
Comment (Manosmer) [reply test/unit/cli/parse-options-test.js]: I was just playing with test cases for the moment. I will leave them as a final job. I would like to finish with the code at first.

File: test/unit/cli/parse-options-test.js (hunk 7 above)
Comment (Manosmer) [reply test/unit/cli/parse-options-test.js]: For my code, arguments `--dbUrlUsername` and `--dbUrlPassword` have a higher priority than auth details provided in `--dbUrl` (I think it's more logically correct), thus they will override the auth details included in `--dbUrl`. I am going to rewrite the tests, add more of them and describe each one of them clearly

File: bin/start.js (hunk 1 above)
Comment (gr2m) [reply bin/start.js]: My guess is that it should go directly to the place where we parse the URL. If the parsed URL has no authentication, then we should log an explanation with `log.error`

Comment (Manosmer) [reply bin/start.js]: The warning is present to inform the users in case they provided auth details already encoded in URL format. In that case, if the user wanted to pass `http://john@doe.com:pass@example.com`, but in an already encoded format, namely `http://john%40doe.com:pass@example.com`, the symbol `%` in the username would be encoded again and the URL would be: `http://john%4040doe.com:pass@example.com`. This is, obviously, wrong.

Comment (gr2m) [reply bin/start.js]: Agree, but it’s the wrong place to show this warning. It should go to the place the parsing is happening

File: test/unit/cli/parse-options-test.js (hunk 7 above)
Comment (gr2m) [reply test/unit/cli/parse-options-test.js]: I agree with the priority. I would still write a test for it so we don’t accidentally break behavior in future. It would also be a nice-to-have to inform the user that a username/password is set in both `dbUrl` and `dbUrlUsername` and that the former one is being ignored

File: test/unit/cli/parse-options-test.js (hunk 5 above)
Comment (Manosmer) [reply test/unit/cli/parse-options-test.js:100]: No it's not 😛. It's in case the user's username starts with https:// 😉

File: test/unit/cli/parse-options-test.js (hunk 7 above)
Comment (Manosmer) [reply test/unit/cli/parse-options-test.js]: I think in my code I warn the user for the override. Also, I will split the code and create a new file (cli/utils/create-auth-db-url.js) just like you proposed. So it would be required to transfer some of the current tests to another `*-test.js` file

**Comment by Manosmer** [comment]
Hello @gr2m. I would like to inform you that I will be off until Sunday due to some difficulties. I will start fixing this PR from Monday. Sorry for any inconvenience.

**Comment by gr2m** [comment]
no worries, thanks for keeping us posted

**Comment by Manosmer** [comment]
At last! First of all, good day @gr2m! Sorry for my absence. I finally found some time to focus on this project and I think that it is finished and working fine. I have only one issue I cannot resolve here: https://github.com/hoodiehq/hoodie/blob/dbUrl-specialChars-fix/test/unit/cli/parse-options-test.js#L195 . Test gives back `not ok path must be a string`. Can you help me with that? I think after that we will finish with this one.

**Comment by gr2m** [comment]
awesome, thanks! 

> I have only one issue I cannot resolve here: https://github.com/hoodiehq/hoodie/blob/dbUrl-specialChars-fix/test/unit/cli/parse-options-test.js#L195 . Test gives back not ok path must be a string

You need to add `dbAdapter: 'pouchdb-adapter-fs'` to the options passed to `parseOptions`, otherwise you try to require(undefined) in https://github.com/hoodiehq/hoodie/blob/e9fd5e143c9ff01f6bbe43e34428c65fa8feaeb4/cli/parse-options.js#L63

You can then test if the adapter is `fs` as expected with

```js
var config = parseOptions({ ... })
t.is(config.PouchDB.preferredAdapters[0], 'fs')
````

**Comment by gr2m** [comment]
by the way, check out debugging Node with Chrome Dev Tools: https://nodejs.org/api/debugger.html#debugger_v8_inspector_integration_for_node_js

Add a `debugger` on top of the failing test, then run the tests with `node --inspect --debug-brk test/unit/cli/parse-options-test.js`. It’s super awesome ✨

**Comment by Manosmer** [comment]
Awesome, @gr2m! Thank you

File: .gitignore [hunk 8]
```diff
@@ -5,3 +5,4 @@ node_modules
 .hoodie
 .nyc_output
 docs/_build/
+.vscode
```
Comment (gr2m) [inline .gitignore]: can you leave this out of the `.gitignore`? You can add it to a `.gitignore` in folder above the repository. I have things like `node_modules` in `~/.gitignore`

Other than that this is good to merge :)

**Review by gr2m — CHANGES_REQUESTED** [review]

File: .gitignore (hunk 8 above)
Comment (Manosmer) [reply .gitignore]: Allright 😄

File: cli/options.js (hunk 2 above)
Comment (gr2m) [reply cli/options.js]: can you please remove the `(if required)` in the descriptions above?

**Comment by Manosmer** [comment]
@gr2m I think it's ready to go now 😛

**Review by gr2m — APPROVED** [review]
well done 👏

**Comment by gr2m** [comment]
ugh totally forgot to clean up commits

**Comment by Litarhis** [comment]
Can the corresponding branch be deleted or is it still useful?

**Comment by gr2m** [comment]
you can delete them once they are merged :)

**Comment by Manosmer** [comment]
Because you said something about cleaning up the commits... I didn't catch that..:( also sorry for restoring and deleting... I am from my mobile's small screen

**Comment by gr2m** [comment]
no worries, fixed it
