### PR TITLE
Portability #872

### LINKED ISSUE #872: npm start command fails
Hello!

I've come across the hoodie project this morning and wanted to try it out; however, I'm running in to a little problem. Using the commands in the readme, I cloned the repo and installed hoodie. When I attempt the start command... I am faced with this:
hoodie start issue

I haven't started to dig in to the problem myself yet, so I hope someone may have an answer... else, I guess I'll figure it out on my own!

Thanks in advance for any advice/help that can be given. :)

### PR DESCRIPTION
**Pull request by md37**
I fixed #872 npm start for Windows by adding portable script.js in package.json.

### CODE REVIEW

**Review by jtdorseyiii — APPROVED** [review]
Bravo! I can now clone hoodie, install and start it with these changes!

**Comment by Terreii** [comment]
Sadly I have to inform you, that this isn't working on macOS. `require('os').type() === 'Darwin'` on macOS.

I would recommend that you check if the os is windows else handle it as unix.

File: start.js [hunk 1]
```diff
@@ -0,0 +1,20 @@
...
+
+function onLog (data) {
+  console.log(data.toString())
+}
+
+function onError (data) {
+  console.error(data.toString())
+}
+
+if (os.type() === 'Linux') {
```
Comment (Terreii) [inline start.js]: Sadly I have to inform you that this isn't working on macOS. `require('os').type() === 'Darwin'` on macOS.

```suggestion
if (os.type() === 'Windows_NT') {
  start = spawn('node', ['bin\\start.js'])
} else {
  start = spawn('./bin/start.js')
}
```

Comment (Terreii) [inline start.js]: Sadly I have to inform you, that this won't work on macOS. require('os').type() === 'Darwin' on macOS.

I would recommend that you check if the os is windows else handle it as unix.
```suggestion
if (os.type() === 'Windows_NT') {
  start = spawn('node', ['bin\\start.js'])
} else {
  start = spawn('./bin/start.js')
}
```

Comment (Terreii) [reply start.js]: sorry I don't know how to delete multiple lines in an review. You have to delete the else if block, too.

Comment (md37) [reply start.js]: Fixed

**Review by gr2m — APPROVED** [review]
cheers
